apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8989
  liveness:
    path: /sosialhjelp/mock-alt-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/mock-alt-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/mock-alt-api/internal/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: digisos
        - application: sosialhjelp-proxy-dev
        - application: sosialhjelp-proxy-mock
    inbound:
      rules:
        - application: digisos
        - application: sosialhjelp-proxy-dev
        - application: sosialhjelp-proxy-mock
        - application: sosialhjelp-modia-api-mock
        - application: sosialhjelp-innsyn-api-mock
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-soknad-api-mock
        - application: sosialhjelp-soknad-api
        - application: sosialhjelp-kommune-service-mock
  resources:
    limits:
      cpu: 750m
      memory: 2Gi
    requests:
      cpu: 2m
      memory: 512Mi
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
