apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-mock-alt-api
  namespace: {{namespace}}
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8989
  liveness:
    path: /sosialhjelp/mock-alt-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/mock-alt-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/mock-alt-api/internal/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: {{webProxyEnabled}}
  vault:
    enabled: {{vaultEnabled}}
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
{{#if isGcp}}
  accessPolicy:
    outbound:
      rules:
        - application: digisos
    inbound:
      rules:
        - application: digisos
        - application: sosialhjelp-modia-api
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-soknad-api
        - application: sosialhjelp-dialog-api-gcp
{{/if}}
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 2m
      memory: 256Mi
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
