# suppress inspection "SpringBootApplicationProperties" for whole file

server:
  port: 8989
  servlet:
    context-path: '/sosialhjelp/mock-alt-api'

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 150MB

logging:
  level:
    root: INFO
    no.nav.sbl.sosialhjelp_mock_alt: DEBUG
    org.springframework.web: INFO

host_address: ${HOST_ADDRESS:http://localhost:8989/}
cookie_domain: ${COOKIE_DOMAIN:localhost}
loginurl: ${LOGINURL:http://localhost:3008/sosialhjelp/mock-alt/login}
filter_soknader_on_fnr: ${FILTER_SOKNADER_ON_FNR:true}

springdoc:
  swagger-ui.path: swagger-ui.html
  paths-to-exclude:
    - "/internal/**"
    - "/pdl_endpoint_url" # graphql endpoint

mock-oauth2-server:
  port: 4321

soknad-api-via-docker-compose: ${SOKNAD_API_VIA_DOCKER_COMPOSE:false}
innsyn-api-via-docker-compose: ${INNSYN_API_VIA_DOCKER_COMPOSE:false}
modia-api-via-docker-compose: ${MODIA_API_VIA_DOCKER_COMPOSE:false}

# sett SOKNAD_FRONTEND_BASEURL som env variabel hvis lenke til ettersendelse-side skal bli korrekt ved lokal kjøring, eks: http://localhost:3000/sosialhjelp/soknad
soknad-frontend-baseurl: ${SOKNAD_FRONTEND_BASEURL:https://digisos.ekstern.dev.nav.no/sosialhjelp/soknad}
