apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-mock-alt-api-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  imagePullPolicy: Always
  port: 8989
  liveness:
    path: /sosialhjelp/mock-alt-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/mock-alt-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
  ingresses:
    - "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt-api"
  accessPolicy:
    outbound:
      rules:
        - application: sosialhjelp-innsyn-api-mock
      external:
        - host: digisos.ekstern.dev.nav.no
    inbound:
      rules:
        - application: sosialhjelp-proxy-mock
        - application: sosialhjelp-modia-api-mock
        - application: sosialhjelp-innsyn-api-mock
        - application: sosialhjelp-innsyn-mock
        - application: sosialhjelp-soknad-api-mock
        - application: sosialhjelp-kommune-service-mock
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  filesFrom:
    - secret: mock-alt-api-fiks-io-private-key
  envFrom:
    - secret: mock-alt-api-fiks-io-integrasjonspassord
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "digisos-ekstern"
    - name: GCP_PORT
      value: "8989"
    - name: HOST_ADDRESS
      value: "http://sosialhjelp-mock-alt-api-mock/"
    - name: COOKIE_DOMAIN
      value: "ekstern.dev.nav.no"
    - name: LOGINURL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt/login"
