name: 'Build Kotlin, Run Lint and Test'
on:
  push:
    branches:
      - '**' # Build all branches
    tags-ignore:
      - '**' # Don't build any tags
  workflow_dispatch:

jobs:
  build:
    name: 'Build with Gradle'
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Build kotlin, and run tests/lint
        uses: navikt/sosialhjelp-ci/actions/build-kotlin@v2
        with:
          lint: 'false'
