name: Build
on:
  push:
    branches:
      - '**' # Build all branches
    tags-ignore:
      - '**' # Don't build any tags

env:
  ORG_GRADLE_PROJECT_githubUser: x-access-token
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Run tests
        run: ./gradlew test
      - name: Build JAR
        run: ./gradlew clean shadowJar -x test
      - name: Login to GitHub package registry
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_REPOSITORY} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Create docker image tags
        run: |
          PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)
          echo "docker.pkg.github.com/$GITHUB_REPOSITORY/$PROJECT_NAME:$VERSION" > DOCKER_TAG
        env:
          VERSION: ${{ steps.artifact-version.outputs.version }}
      - name: Build docker image
        run: docker build -t $(cat DOCKER_TAG) .
      - name: Create tag and release
        # TODO: Bytt ut med upstream når/hvis https://github.com/actions/create-release/pull/32 merges
        uses: fleskesvor/create-release@feature/support-target-commitish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.artifact-version.outputs.version }}
          release_name: ${{ steps.artifact-version.outputs.version }}
          commitish: ${{ github.sha }}
      - name: Push docker image
        run: |
          cat DOCKER_TAG
          docker push $(cat DOCKER_TAG)
