name: 'Build Kotlin, Run Lint and Test'
on:
  push:
    branches:
      - '**' # Build all branches
    tags-ignore:
      - '**' # Don't build any tags
  workflow_dispatch:

jobs:
  build:
    name: 'Build with Docker'
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to ghcr.io'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Version from Commit'
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@v2

      - name: 'Setup QEMU and Docker Buildx'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Create and push multi-arch Docker image'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.version }}
            ${{ github.ref == 'refs/heads/master' && env.DOCKER_IMAGE + ':latest' }}
          platforms: linux/amd64,linux/arm64
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}