name: Code Analysis and Dependency Submission

on:
  push:
    branches:
      - master
  schedule: ## Kjører kl. 05:00 mandag -> fredag (schedule kjører bare for Default branch)
    - cron: '0 5 * * 1-5'

jobs:
  analyze_code:
    name: Analyze Code
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: navikt/sosialhjelp-ci/.github/workflows/codeql_java.yml@master

  dependency_submission:
    name: Dependency Submission Gradle
    permissions:
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/dependency_submission_gradle.yml@master