name: 'Remove Old Images'
on:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  remove-images:
    name: 'Remove old images job except 50 most recent'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'sosialhjelp-mock-alt-api/sosialhjelp-mock-alt-api'
          package-type: 'container'
          min-versions-to-keep: 50
