name: 'Restart test-envs'
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  restart-testenvs:
    name: 'Restart test-envs'
    uses: navikt/sosialhjelp-ci/.github/workflows/restart_test-envs.yml@main
    secrets: inherit
    with:
      to-mock: true
